### ISSUE TITLE
Strange error on Windows

### ISSUE THREAD

**Issue by mrexodia** [mrphrazer/hitb2021ams_deobfuscation#6]
When following the instructions on Windows I got a strange error about the `build` folder not existing:

```
D:\CodeBlocks\hitb2021ams_deobfuscation>python3 -m pip install -r requirements.txt
Obtaining file:///D:/CodeBlocks/hitb2021ams_deobfuscation/msynth/miasm (from -r requirements.txt (line 6))
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Admin\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'D:\\CodeBlocks\\hitb2021ams_deobfuscation\\msynth\\miasm\\setup.py'"'"'; __file__='"'"'D:\\CodeBlocks\\hitb2021ams_deobfuscation\\msynth\\miasm\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Admin\AppData\Local\Temp\pip-pip-egg-info-_zpgzqkf'
         cwd: D:\CodeBlocks\hitb2021ams_deobfuscation\msynth\miasm\
    Complete output (23 lines):
    building
    build with 'all'
    running egg_info
    creating C:\Users\Admin\AppData\Local\Temp\pip-pip-egg-info-_zpgzqkf\miasm.egg-info
    writing C:\Users\Admin\AppData\Local\Temp\pip-pip-egg-info-_zpgzqkf\miasm.egg-info\PKG-INFO
    writing dependency_links to C:\Users\Admin\AppData\Local\Temp\pip-pip-egg-info-_zpgzqkf\miasm.egg-info\dependency_links.txt
    writing requirements to C:\Users\Admin\AppData\Local\Temp\pip-pip-egg-info-_zpgzqkf\miasm.egg-info\requires.txt
    writing top-level names to C:\Users\Admin\AppData\Local\Temp\pip-pip-egg-info-_zpgzqkf\miasm.egg-info\top_level.txt
    writing manifest file 'C:\Users\Admin\AppData\Local\Temp\pip-pip-egg-info-_zpgzqkf\miasm.egg-info\SOURCES.txt'
    adding license file 'LICENSE' (matched pattern 'LICEN[CS]E*')
    reading manifest file 'C:\Users\Admin\AppData\Local\Temp\pip-pip-egg-info-_zpgzqkf\miasm.egg-info\SOURCES.txt'
    writing manifest file 'C:\Users\Admin\AppData\Local\Temp\pip-pip-egg-info-_zpgzqkf\miasm.egg-info\SOURCES.txt'
    C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\dist.py:477: UserWarning: The version specified ('git-archive.dev$Format:%h') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
      warnings.warn(
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "D:\CodeBlocks\hitb2021ams_deobfuscation\msynth\miasm\setup.py", line 344, in <module>
        buil_all()
      File "D:\CodeBlocks\hitb2021ams_deobfuscation\msynth\miasm\setup.py", line 296, in buil_all
        for dirname in os.listdir(build_base):
    FileNotFoundError: [WinError 3] The system cannot find the path specified: 'build'
    build all
    build
    ----------------------------------------
WARNING: Discarding file:///D:/CodeBlocks/hitb2021ams_deobfuscation/msynth/miasm. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I think for some reason the requirements script doesn't trigger the necessary `python setup.py build`. I already opened #5 to clarify the instructions but I wonder if it's possible to handle this automatically somehow.

**Comment by mrphrazer** [comment]
TBH, I don't have any idea what's going on. Miasm`s `setup.py` is definitely executed, but it seems to behave differently if you call it directly.  Your PR makes it usable for Windows, I'll keep it like that for now.
